### ISSUE TITLE
Firefox doesnt render innerText

### ISSUE THREAD

**Issue by heron2014** [node-girls/workshop#10]
[L15](https://github.com/node-girls/workshop/blob/58b9771f7b967e297c3f4694352e4d4ccb4ce6b1/public/script.js#L15)

which cause in Firefox to show empty posts : 
![posts](https://cloud.githubusercontent.com/assets/8476884/10947094/ffbeec68-831d-11e5-8a4b-7581ba1fe047.png)

**Comment by NataliaLKB** [comment]
Yay! Thanks @heron2014
