### ISSUE TITLE
Do you have code to get the tests passing?

### ISSUE THREAD

**Issue by RabeaGleissner** [node-girls/workshop#26]
Hi ladies!

Really good workshop yesterday, enjoyed the whole day! :clap: 

I was wondering if you could publish the code that passes the tests? I tried to complete the task by following the tests but I think my code is therefore structured a bit differently from the code in the example branch... Would be interested to see how it needs to be done for the tests to pass. 

Thank you! (no rush by the way, whenever you have time...)

**Comment by NataliaLKB** [comment]
Hey @RabeaGleissner!

If you take a look at the `example` branch all the tests should be passing there. It follows the structure provided in `file_structure.md`

Let me know if you have any questions!

**Comment by RabeaGleissner** [comment]
@NataliaLKB Ahhh, thank you very much! I was sure I tried running the tests on the example branch on Sunday but clearly I must have messed that up! I tried again just now and all are passing wonderfully :smile_cat: 
Sorry about that... 
*_goes back to learning node *_

**Comment by NataliaLKB** [comment]
I am glad it is working for you now!

We don't have as high a test coverage as I would like for this example :disappointed:.

Will try on the weekend to make it a bit better.
