### ISSUE TITLE
static is a reserved word

### ISSUE THREAD

**Issue by heron2014** [node-girls/workshop#4]
This could be a potential issue in a future using reserved words.

[L5](https://github.com/node-girls/workshop/blob/bb563ceafd6ccaae87b46cff62717113e3d41b84/handlers.js#L5)

Reference: [Lexical grammar](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar)

**Comment by NataliaLKB** [comment]
Excellent point!! Issue regarding their docs have also been opened https://github.com/cloudhead/node-static/issues/147

I will send a PR changing the name of this variable.
