### ISSUE TITLE
We Need Tests

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/workshop#7]
Who is writing tests again? 

Do you need help?

**Comment by claireinez** [comment]
@msmichellegar is writing them, I believe!

**Comment by NataliaLKB** [comment]
Great! Happy to help if you need it :).

**Comment by msmichellegar** [comment]
I have tests passing, woo! In the "tests" branch. I'm on a roll if you didn't get around to the other tests @NataliaLKB :)

**Comment by NataliaLKB** [comment]
First bit of tests done in #15 . Need more though to get a good test coverage :). They will need to be all unit tests

**Comment by NataliaLKB** [comment]
@msmichellegar It would be great if you could do more. What tests are you doing?

I am going to make a PR for istanbul

**Comment by NataliaLKB** [comment]
Closed as we have tests now :)
