### ISSUE TITLE
jquery?

### ISSUE THREAD

**Issue by NataliaLKB** [node-girls/workshop#9]
I think we should remove it.

Unless anyone can think of a good reason?

I am ready with a PR :)

**Comment by claireinez** [comment]
I was thinking about that too actually, though I realised that most of the attendees are probably front-end developers who are familiar with jQuery, and less familiar with the vanilla JavaScript ways of doing things.

**Comment by NataliaLKB** [comment]
I think it is less a questions of familiarity, and more of best practise. We are loading in jquery to only use `$.ajax` when we are using [vanilla js dom manipulation](https://github.com/node-girls/workshop/blob/master/public/script.js#L8). Wouldn't it be better to either use all vanilla JavaScript, or use something like [request](https://www.npmjs.com/package/browser-request)?

**Comment by NataliaLKB** [comment]
Or use jquery for dom manipulation.

**Comment by iteles** [comment]
I'm with @NataliaLKB.

If we're not using a framework for Node, we should be using vanilla JS. One helps the other. :+1:

**Comment by claireinez** [comment]
Good point guys! @NataliaLKB I think you should make the PR :)
